[package]
name = "try_actix-web"
version = "0.1.0"
authors = ["f-jost <9694162+f-jost@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
